### ISSUE TITLE
Email field not allowed when no authentication is selected

### ISSUE THREAD

**Issue by dostuffthatmatters** [fastsurvey/backend#59]
With a config with `authentication = 'open'` an email field cannot be included.

I'd strongly prefer if having an email field without any authentication was allowed.

Right now if I have a finished survey and want to switch from 'email' authentication to 'open' then I cannot do so without removing the email field and adding a text field in the same place.

Do you agree on that?

**Comment by empicano** [comment]
I don't see anything against it. Let's spin your idea further, what do you think about putting a "verify" checkbox on an email field in the editor (translating to a `verify=True/False` email field property in the config)? When it's selected we verify the email, otherwise not.

- the verification logic choice is closer to the actual field, which makes it a bit more intuitive in my opinion.
- the problem would be solved as well, because we wouldn't need any `authentication` property anymore.

I don't have a good idea for how we could integrate the coming `invite` authentication into this yet, though.

**Comment by dostuffthatmatters** [comment]
I really like the `verify` property on email fields - great idea! For now we can remove the verify property.

Once we can offer invite lists (which would be managed separately anyways) there can be a button "add invite list". The validation only complains if you set both "invite" and "email.verify".

How do you like that?

**Comment by empicano** [comment]
Sounds good! Concerning validation, I'd then allow an unbounded number of email fields, but at most one email field that's supposed to be verified, no?

**Comment by dostuffthatmatters** [comment]
To clarify: Yes, the only check is `len(email field with verify=true)` <= 1.
