### ISSUE TITLE
Make config error messages more specific

### ISSUE THREAD

**Issue by dostuffthatmatters** [fastsurvey/backend#61]
Right now, most responses I get with error messages from the backend are `400 {"detail":"invalid configuration"}`.

This does not help a lot :D - so I have to run the backend locally every time this happens.

Could you make the details for invalid configs more specific please?

I guess that has not been implemented yet since cerberus delivers a dynamic error message format (dict inside dict, etc.). Maybe just add another field to the response so that the details-field remains readable: `{"detail":"invalid configuration", "cerberus_output": "..."}`.

**Comment by dostuffthatmatters** [comment]
Oh, I just noticed and remembered that you are not using cerberus there.

https://github.com/fastsurvey/backend/blob/02cabf211064de40577dcbed0c7c5acb76de9cdb/app/validation.py#L92
Very clean and readable validation, but has to be rewritten if one wants any error message out of there :D

How do you like the following?

```python
checks = [
    type(value) is dict,
    set(value.keys()) == self._FIELD_KEYS['configuration'],
    ...,
]

logging.debug([i for i, c in enumerate(checks) if not c])  # failed check indices
return all(checks)
```

**Comment by dostuffthatmatters** [comment]
![](https://media.giphy.com/media/7TqDUEMT50uAztuB83/giphy.gif)

**Comment by empicano** [comment]
I like that she angrily throws it at me instead of putting it in the box in the end 😄

That's a good point, the error response is too general. I don't really like how the accounts/configurations/submissions are validated at the moment. FastAPI usually validates requests via pydantic and gives back a `422 Validation Error` of this form:

```
{
  "detail": [
    {
      "loc": [
        "string"
      ],
      "msg": "string",
      "type": "string"
    }
  ]
}
```

which points you to the location and the type of the fault. I prefer this one over your two suggestions even, because it hides the implementation details, but nonetheless gives information what exactly is not valid. I avoided pydantic originally due to some painpoints, but I think using it could be possible after all. I wanted to switch back to pydantic for a while, I'll see if I can improve the error message along with it!
